import json

EN = {
"nav.home":"Home","dd.academy":"Academy","nav.contact":"Contact","mob.cta":"Request a Quote →","ham.label":"Open Menu",
"hero.eyebrow":"// Ankara, Türkiye · Industrial Sourcing & Project Supply Partner · MENA & Africa",
"hero.h1":"INDUSTRIAL SOURCING.<br><span class=\"accent\">PROJECT SUPPLY.</span><br>ONE ACCOUNTABLE PARTNER.",
"hero.sub":"VORQA connects industrial requirements with qualified suppliers and specialized plant partners, managing technical, commercial and delivery coordination from request to destination.",
"hero.cta1":"Request a Quote","hero.cta2":"Explore Our Capabilities","hero.eco":"What We Coordinate","hero.scroll":"Scroll",
"tab.1":"Concrete Plants","tab.2":"Complete Galvanizing","tab.3":"Waste-to-Energy","tab.4":"Crushing & Screening","tab.5":"Industrial Sourcing",
"tick.1":"Concrete Plants","tick.2":"Complete Galvanizing","tick.3":"Waste-to-Energy","tick.4":"Crushing & Screening","tick.5":"Industrial Sourcing",
"about.num":"§ 01 / About VORQA",
"about.p1":"VORQA is a customer-side industrial sourcing, project supply and coordination partner — not a broker, not a general trading firm. We clarify technical requirements, select the right manufacturer or specialized plant partner, compare technical and commercial offers, and coordinate multi-vendor project packages from request to delivery.",
"about.p2":"Every recommendation runs through a network of 1,000+ verified Turkish suppliers, turning a scattered and high-risk industrial supply chain into a single, accountable point of contact — from clarification through production follow-up, documentation and delivery.",
"btn.contact":"Contact Us",
"s1.lbl":"Verified Supplier Network","s2.val":"MENA & Africa","s2.lbl":"Target Markets",
"svc.num":"§ 02 / Services","svc.title":"How we support your project.",
"svc1.num":"01","svc1.title":"Industrial Sourcing","svc1.body":"Technical requirements matched with qualified manufacturers and suppliers.",
"svc2.num":"02","svc2.title":"Project Supply & Consolidation","svc2.body":"Multiple products and vendors managed as one coordinated supply package.",
"svc3.num":"03","svc3.title":"Technical & Commercial Coordination","svc3.body":"Clarifications, offer comparison, documentation and supplier follow-up handled through one accountable team.",
"svc4.num":"04","svc4.title":"International Delivery Coordination","svc4.body":"Production follow-up, consolidation, export documentation and delivery planning coordinated to destination.",
"ind.num":"§ 03 / Industries & Supply Groups","ind.partners.label":"Partner Plant Solutions","co.partner.tag":"Partner Plant Solution","btn.explore":"Request a Quote",
"co1.tag":"Concrete Plants","co1.desc":"Complete concrete batching plant solutions — from requirement clarification to partner selection and project coordination.",
"co2.tag":"Complete Galvanizing Plants","co2.desc":"Complete hot-dip galvanizing plant solutions, delivered through a specialized manufacturing partner and coordinated by VORQA.",
"co3.tag":"Waste-to-Energy Plants","co3.desc":"Complete waste-to-energy plant solutions delivered through a specialized manufacturing partner, coordinated from request to delivery.",
"co4.tag":"Crushing & Screening Plants","co4.desc":"Complete crushing and screening plant solutions matched to project requirements through a specialized manufacturing partner.",
"sg.label":"Industrial Supply Groups",
"sg1":"Industrial Spare Parts & MRO","sg2":"Technical Equipment Sourcing","sg3":"Project-Based Supply Packages",
"sg4":"Electrical, Automation & Instrumentation Components","sg5":"Industrial Piping, Valves & Flow-Control Components",
"sg6":"Insulation, HVAC & Project Support Materials","sg7":"Custom Fabrication & Project-Specific Requirements",
"sg.note":"These groups are not a closed product catalog — VORQA manages manufacturer, distributor, OEM and technically verified equivalent channels on request.",
"how.num":"§ 04 / How We Work","how.title":"From request to delivery, one accountable partner.",
"how1.num":"01","how1.title":"Requirement Review","how1.body":"We review your project requirement and technical scope together.",
"how2.num":"02","how2.title":"Technical Clarification","how2.body":"Open questions, specifications and constraints are clarified before any offer is compared.",
"how3.num":"03","how3.title":"Supplier / Partner Selection","how3.body":"The right manufacturer, supplier or specialized plant partner is matched from our verified network.",
"how4.num":"04","how4.title":"Offer & Order Coordination","how4.body":"Technical and commercial offers are compared and consolidated into one coordinated order.",
"how5.num":"05","how5.title":"Production, Documentation & Delivery Follow-Up","how5.body":"Production, quality documentation, logistics and delivery are followed through to destination.",
"fcta.num":"§ 05 / Get Started","fcta.title":"Let’s define your requirement.","fcta.body":"Share your project with us — our team responds within 48 hours.","fcta.btn":"Request a Quote",
"foot.copy":"© 2026 Vorqa Global — All Rights Reserved","ad.val":"Ankara, Türkiye",
}

TR = {
"nav.home":"Ana Sayfa","dd.academy":"Akademi","nav.contact":"İletişim","mob.cta":"Teklif Al →","ham.label":"Menüyü Aç",
"hero.eyebrow":"// Ankara, Türkiye · Endüstriyel Tedarik & Proje Koordinasyon Partneri · MENA & Afrika",
"hero.h1":"ENDÜSTRİYEL TEDARİK.<br><span class=\"accent\">PROJE TEDARİĞİ.</span><br>TEK MUHATAP PARTNER.",
"hero.sub":"VORQA, endüstriyel ihtiyaçları doğrulanmış tedarikçiler ve uzman tesis partnerleriyle buluşturur; teknik, ticari ve teslimat koordinasyonunu talepten hedefe kadar yönetir.",
"hero.cta1":"Teklif Al","hero.cta2":"Yetkinliklerimizi Keşfedin","hero.eco":"Koordine Ettiklerimiz","hero.scroll":"Kaydır",
"tab.1":"Beton Santralleri","tab.2":"Komple Galvaniz Tesisleri","tab.3":"Atık-Enerji Dönüşümü","tab.4":"Kırma & Eleme","tab.5":"Endüstriyel Tedarik",
"tick.1":"Beton Santralleri","tick.2":"Komple Galvaniz Tesisleri","tick.3":"Atık-Enerji Dönüşümü","tick.4":"Kırma & Eleme","tick.5":"Endüstriyel Tedarik",
"about.num":"§ 01 / VORQA Hakkında",
"about.p1":"VORQA; müşteri tarafında çalışan bir endüstriyel tedarik, proje tedariği ve koordinasyon partneridir — komisyoncu ya da genel bir trading firması değildir. Teknik ihtiyacı netleştirir, doğru üretici veya uzman tesis partnerini seçer, teknik ve ticari teklifleri karşılaştırır; çok tedarikçili proje paketlerini talepten teslimata kadar koordine eder.",
"about.p2":"Her öneri, 1.000+ doğrulanmış Türk tedarikçiden oluşan ağımızdan geçer; dağınık ve riskli bir endüstriyel tedarik zincirini — netleştirmeden üretim takibine, dokümantasyona ve teslimata kadar — tek ve sorumlu bir temas noktasına dönüştürür.",
"btn.contact":"Bize Ulaşın",
"s1.lbl":"Doğrulanmış Tedarikçi Ağı","s2.val":"MENA & Afrika","s2.lbl":"Hedef Pazarlar",
"svc.num":"§ 02 / Hizmetler","svc.title":"Projenizi nasıl destekliyoruz.",
"svc1.num":"01","svc1.title":"Endüstriyel Tedarik","svc1.body":"Teknik ihtiyaçlar, doğrulanmış üretici ve tedarikçilerle eşleştirilir.",
"svc2.num":"02","svc2.title":"Proje Tedariği & Konsolidasyon","svc2.body":"Birden fazla ürün ve tedarikçi, tek koordine edilen tedarik paketi olarak yönetilir.",
"svc3.num":"03","svc3.title":"Teknik & Ticari Koordinasyon","svc3.body":"Netleştirme, teklif karşılaştırma, dokümantasyon ve tedarikçi takibi tek bir sorumlu ekip üzerinden yürütülür.",
"svc4.num":"04","svc4.title":"Uluslararası Teslimat Koordinasyonu","svc4.body":"Üretim takibi, konsolidasyon, ihracat dokümantasyonu ve teslimat planlaması hedefe kadar koordine edilir.",
"ind.num":"§ 03 / Sektörler & Tedarik Grupları","ind.partners.label":"Partner Tesis Çözümleri","co.partner.tag":"Partner Tesis Çözümü","btn.explore":"Teklif Al",
"co1.tag":"Beton Santralleri","co1.desc":"Komple beton santrali çözümleri — ihtiyacın netleştirilmesinden partner seçimine ve proje koordinasyonuna kadar.",
"co2.tag":"Komple Galvaniz Tesisleri","co2.desc":"Uzman üretici partner üzerinden sunulan, VORQA tarafından koordine edilen komple sıcak daldırma galvaniz tesisi çözümleri.",
"co3.tag":"Atık-Enerji Dönüşüm Tesisleri","co3.desc":"Uzman üretici partner üzerinden sunulan, talepten teslimata koordine edilen komple atık-enerji tesisi çözümleri.",
"co4.tag":"Kırma & Eleme Tesisleri","co4.desc":"Uzman üretici partner üzerinden proje ihtiyacına uygun eşleştirilen komple kırma-eleme tesisi çözümleri.",
"sg.label":"Endüstriyel Tedarik Grupları",
"sg1":"Endüstriyel Yedek Parça & MRO","sg2":"Teknik Ekipman Tedariği","sg3":"Proje Bazlı Tedarik Paketleri",
"sg4":"Elektrik, Otomasyon & Enstrümantasyon Bileşenleri","sg5":"Endüstriyel Boru Hattı, Vana & Akış Kontrol Bileşenleri",
"sg6":"Yalıtım, HVAC & Proje Destek Malzemeleri","sg7":"Özel İmalat & Projeye Özel Gereksinimler",
"sg.note":"Bu gruplar kapalı bir ürün kataloğu değildir — VORQA, talebe göre üretici, distribütör, OEM ve teknik olarak doğrulanmış muadil kanalları yönetir.",
"how.num":"§ 04 / Nasıl Çalışırız","how.title":"Talepten teslime, tek muhatap.",
"how1.num":"01","how1.title":"Talep İncelemesi","how1.body":"Proje ihtiyacınızı ve teknik kapsamı birlikte inceleriz.",
"how2.num":"02","how2.title":"Teknik Netleştirme","how2.body":"Herhangi bir teklif karşılaştırılmadan önce açık sorular, şartname ve kısıtlar netleştirilir.",
"how3.num":"03","how3.title":"Tedarikçi / Partner Seçimi","how3.body":"Doğrulanmış ağımızdan doğru üretici, tedarikçi veya uzman tesis partneri eşleştirilir.",
"how4.num":"04","how4.title":"Teklif & Sipariş Koordinasyonu","how4.body":"Teknik ve ticari teklifler karşılaştırılır, tek koordine edilen siparişte birleştirilir.",
"how5.num":"05","how5.title":"Üretim, Dokümantasyon & Teslimat Takibi","how5.body":"Üretim, kalite dokümantasyonu, lojistik ve teslimat hedefe ulaşana kadar takip edilir.",
"fcta.num":"§ 05 / Başlayalım","fcta.title":"İhtiyacınızı birlikte netleştirelim.","fcta.body":"Projenizi bizimle paylaşın — ekibimiz 48 saat içinde yanıt verir.","fcta.btn":"Teklif Al",
"foot.copy":"© 2026 Vorqa Global — Tüm Hakları Saklıdır","ad.val":"Ankara, Türkiye",
}

AR = {
"nav.home":"الرئيسية","dd.academy":"الأكاديمية","nav.contact":"تواصل معنا","mob.cta":"اطلب عرض سعر ←","ham.label":"افتح القائمة",
"hero.eyebrow":"// أنقرة، تركيا · شريك التوريد الصناعي وتنسيق المشاريع · الشرق الأوسط وأفريقيا",
"hero.h1":"التوريد الصناعي.<br><span class=\"accent\">تزويد المشاريع.</span><br>شريك واحد مسؤول.",
"hero.sub":"تربط VORQA المتطلبات الصناعية بموردين مؤهلين وشركاء تصنيع متخصصين، وتدير التنسيق الفني والتجاري وتنسيق التسليم من الطلب حتى الوجهة.",
"hero.cta1":"اطلب عرض سعر","hero.cta2":"استكشف قدراتنا","hero.eco":"ما ننسقه","hero.scroll":"مرر للأسفل",
"tab.1":"محطات الخرسانة","tab.2":"منشآت الجلفنة الكاملة","tab.3":"تحويل النفايات إلى طاقة","tab.4":"التكسير والغربلة","tab.5":"التوريد الصناعي",
"tick.1":"محطات الخرسانة","tick.2":"منشآت الجلفنة الكاملة","tick.3":"تحويل النفايات إلى طاقة","tick.4":"التكسير والغربلة","tick.5":"التوريد الصناعي",
"about.num":"§ 01 / عن VORQA",
"about.p1":"VORQA شريك توريد صناعي وتزويد مشاريع وتنسيق يعمل لصالح العميل — وليست وسيطاً أو شركة تجارة عامة. نقوم بتوضيح المتطلبات الفنية، واختيار المصنّع أو شريك المنشأة المتخصص المناسب، ومقارنة العروض الفنية والتجارية، وتنسيق حزم المشاريع متعددة الموردين من الطلب حتى التسليم.",
"about.p2":"تمر كل توصية عبر شبكتنا المكوّنة من أكثر من 1000 مورّد تركي معتمد، لتحويل سلسلة توريد صناعية متفرقة وعالية المخاطر إلى نقطة اتصال واحدة مسؤولة — من التوضيح إلى متابعة الإنتاج والتوثيق والتسليم.",
"btn.contact":"تواصل معنا",
"s1.lbl":"شبكة موردين معتمدة","s2.val":"الشرق الأوسط وأفريقيا","s2.lbl":"الأسواق المستهدفة",
"svc.num":"§ 02 / خدماتنا","svc.title":"كيف ندعم مشروعك",
"svc1.num":"01","svc1.title":"التوريد الصناعي","svc1.body":"مطابقة المتطلبات الفنية بمصنّعين وموردين مؤهلين.",
"svc2.num":"02","svc2.title":"تزويد المشاريع والدمج","svc2.body":"إدارة منتجات وموردين متعددين كحزمة توريد واحدة منسقة.",
"svc3.num":"03","svc3.title":"التنسيق الفني والتجاري","svc3.body":"التوضيحات ومقارنة العروض والتوثيق ومتابعة الموردين، كلها عبر فريق واحد مسؤول.",
"svc4.num":"04","svc4.title":"تنسيق التسليم الدولي","svc4.body":"متابعة الإنتاج والتجميع ووثائق التصدير وتخطيط التسليم، منسقة حتى الوجهة.",
"ind.num":"§ 03 / القطاعات ومجموعات التوريد","ind.partners.label":"حلول المنشآت الشريكة","co.partner.tag":"حل منشأة شريكة","btn.explore":"اطلب عرض سعر",
"co1.tag":"محطات الخرسانة","co1.desc":"حلول محطات خرسانة جاهزة كاملة — من توضيح المتطلبات إلى اختيار الشريك وتنسيق المشروع.",
"co2.tag":"منشآت الجلفنة الكاملة","co2.desc":"حلول منشآت جلفنة بالغمس الساخن الكاملة، تُقدّم عبر شريك تصنيع متخصص وتُنسّق من قبل VORQA.",
"co3.tag":"منشآت تحويل النفايات إلى طاقة","co3.desc":"حلول منشآت تحويل النفايات إلى طاقة الكاملة، تُقدّم عبر شريك تصنيع متخصص وتُنسّق من الطلب حتى التسليم.",
"co4.tag":"منشآت التكسير والغربلة","co4.desc":"حلول منشآت تكسير وغربلة كاملة تُطابَق مع متطلبات المشروع عبر شريك تصنيع متخصص.",
"sg.label":"مجموعات التوريد الصناعي",
"sg1":"قطع الغيار الصناعية وصيانة المعدات (MRO)","sg2":"توريد المعدات التقنية","sg3":"حزم التوريد حسب المشروع",
"sg4":"مكونات الكهرباء والأتمتة والقياس والتحكم","sg5":"مكونات الأنابيب الصناعية والصمامات والتحكم بالتدفق",
"sg6":"مواد العزل والتكييف ودعم المشاريع","sg7":"التصنيع المخصص ومتطلبات المشاريع الخاصة",
"sg.note":"هذه المجموعات ليست كتالوج منتجات مغلقاً — تدير VORQA قنوات المصنّعين والموزّعين والمعدات الأصلية والبدائل الموثقة فنياً حسب الطلب.",
"how.num":"§ 04 / كيف نعمل","how.title":"من الطلب حتى التسليم، شريك واحد مسؤول.",
"how1.num":"01","how1.title":"مراجعة المتطلبات","how1.body":"نراجع معك متطلبات مشروعك ونطاقه الفني.",
"how2.num":"02","how2.title":"التوضيح الفني","how2.body":"تُوضّح الأسئلة المفتوحة والمواصفات والقيود قبل مقارنة أي عرض.",
"how3.num":"03","how3.title":"اختيار المورد / الشريك","how3.body":"يُختار المصنّع أو المورد أو شريك المنشأة المتخصص المناسب من شبكتنا المعتمدة.",
"how4.num":"04","how4.title":"تنسيق العروض والطلبات","how4.body":"تُقارَن العروض الفنية والتجارية وتُدمَج في طلب واحد منسق.",
"how5.num":"05","how5.title":"متابعة الإنتاج والتوثيق والتسليم","how5.body":"تُتابَع عمليات الإنتاج وتوثيق الجودة واللوجستيات والتسليم حتى الوجهة.",
"fcta.num":"§ 05 / لنبدأ","fcta.title":"لنحدد متطلبات مشروعك.","fcta.body":"شاركنا مشروعك — يرد فريقنا خلال 48 ساعة.","fcta.btn":"اطلب عرض سعر",
"foot.copy":"© 2026 Vorqa Global — جميع الحقوق محفوظة","ad.val":"أنقرة، تركيا",
}

def dump(d):
    return json.dumps(d, ensure_ascii=False, indent=2)

with open('_new_T_object.txt', 'w', encoding='utf-8') as f:
    f.write("const T = {\n")
    f.write("  tr: " + dump(TR) + ",\n")
    f.write("  en: " + dump(EN) + ",\n")
    f.write("  ar: " + dump(AR) + "\n")
    f.write("};\n")

assert set(EN)==set(TR)==set(AR), (set(EN)^set(TR), set(EN)^set(AR))
print("keys match across all 3 languages:", len(EN))
