const deck=document.getElementById('deck');
const pages=[...document.querySelectorAll('.page')];
const dots=document.getElementById('dots');
let idx=0;
pages.forEach((_,i)=>{const b=document.createElement('button');b.className='dot'+(i===0?' active':'');b.setAttribute('aria-label',`${i+1}. bölüm`);b.onclick=()=>go(i);dots.appendChild(b)});
const dotEls=[...dots.children],prev=document.getElementById('prev'),next=document.getElementById('next');
function updateNav(){dotEls.forEach((d,n)=>d.classList.toggle('active',n===idx));prev.disabled=idx===0;next.disabled=idx===pages.length-1;document.body.classList.toggle('edge-page',idx===0||idx===pages.length-1)}
function go(i){idx=Math.max(0,Math.min(pages.length-1,i));pages[idx].scrollIntoView({behavior:'smooth',inline:'start',block:'nearest'});updateNav()}
prev.onclick=()=>go(idx-1);next.onclick=()=>go(idx+1);
document.getElementById('startBtn').onclick=e=>{e.preventDefault();go(1)};
let raf=0;
deck.addEventListener('scroll',()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const n=Math.round(deck.scrollLeft/deck.clientWidth);if(n!==idx){idx=n;updateNav()}})},{passive:true});
addEventListener('keydown',e=>{if(e.key==='ArrowRight')go(idx+1);if(e.key==='ArrowLeft')go(idx-1);if(e.key==='Escape')document.getElementById('sheet').classList.remove('open')});
updateNav();

const original={};document.querySelectorAll('[data-i]').forEach(el=>original[el.dataset.i]=el.innerHTML);
const strings={
en:{
coverEyebrow:'INDUSTRIAL SOURCING · PROJECT SUPPLY',cover1:'From Requirement',cover2:'to Delivery',coverLead:'Technical clarity, the right source and coordinated execution',coverTag:'Industrial Sourcing · Project Supply · One Accountable Partner',sigTitle:'We turn requirements into a coordinated supply flow',sigText:'Technical evaluation, supplier selection, coordination and delivery under one accountability',c1:'Technical Clarity',c2:'Reliable Supplier Network',c3:'Coordinated Execution',c4:'Reliable Delivery',discover:'Explore the Profile',
idEyebrow:'WHO WE ARE',id1:'One Accountable Partner,',id2:'Coordinated Execution',idText:'VORQA is a Türkiye-based industrial sourcing and project coordination partner. We connect global buyers with reliable manufacturers and specialist solution partners, coordinating technical requirements, commercial terms and supply execution through one accountable point.',p1:'Technical Understanding',p2:'Supplier Reliability',p3:'Quality & Transparency',p4:'Coordination Discipline',workTitle:'How We Work',workSub:'One flow from requirement to delivery',s1:'Understand Need',s2:'Clarify Technicals',s3:'Match',s4:'Coordinate',s5:'Deliver',idVisual:'Right partners · controlled process · one accountability',
scopeEyebrow:'SUPPLY SCOPE',scope1:'Industrial',scope2:'Supply Scope',scopeLead:'Coordinated supply solutions across a broad range of industrial requirements',g1:'Steel & Raw Materials',g2:'Pipes, Tubes, Fittings & Valves',g3:'Pumps, Valves & Flow Equipment',g4:'Motors, Gear Reducers & Power Transmission',g5:'Electrical, Automation & Instrumentation',g6:'Hydraulic & Pneumatic Systems',g7:'Silo & Bulk Handling Equipment',g8:'Fabricated Steel & Structures',g9:'Industrial Plants & Solution Packages',scopeFoot:'We organize the right source according to technical specifications, application and delivery targets',
sysEyebrow:'SPECIALIST SYSTEMS',sys1:'Specialist',sys2:'Systems',sysLead:'Tap a system to view scope, typical content and coordination details',sysA:'Concrete Plants',sysB:'Complete Galvanizing Plants',sysC:'Waste-to-Energy Plants',sysD:'Crushing & Screening Plants',tap:'View details',
contactEyebrow:'CONTACT',contact1:'Contact',contact2:'Us',contactLead:'Contact our team for industrial sourcing, project supply and specialist solution requirements',rfq:'Request a Quote',detailEyebrow:'SPECIALIST SYSTEM',dScope:'Scope',dTypical:'Typical Content',dCoord:'Coordination'
},
ar:{
coverEyebrow:'التوريد الصناعي · توريد المشاريع',cover1:'من الاحتياج',cover2:'إلى التسليم',coverLead:'وضوح فني ومصدر مناسب وتنفيذ منسق',coverTag:'التوريد الصناعي · توريد المشاريع · شريك واحد مسؤول',sigTitle:'نحوّل الاحتياجات إلى مسار توريد منسق',sigText:'تقييم فني واختيار المورد والتنسيق والتسليم ضمن مسؤولية واحدة',c1:'وضوح فني',c2:'شبكة موردين موثوقة',c3:'تنفيذ منسق',c4:'تسليم موثوق',discover:'استكشف الملف',
idEyebrow:'من نحن',id1:'جهة واحدة مسؤولة',id2:'تنفيذ منسق',idText:'VORQA شريك مقره تركيا للتوريد الصناعي وتنسيق المشاريع. نربط المشترين الدوليين بالمصنعين الموثوقين وشركاء الحلول المتخصصين، وننسق المتطلبات الفنية والشروط التجارية وتنفيذ التوريد من نقطة مسؤولية واحدة.',p1:'فهم فني',p2:'موثوقية الموردين',p3:'الجودة والشفافية',p4:'انضباط التنسيق',workTitle:'كيف نعمل',workSub:'مسار واحد من الاحتياج إلى التسليم',s1:'فهم الاحتياج',s2:'توضيح المتطلبات الفنية',s3:'المطابقة',s4:'التنسيق',s5:'التسليم',idVisual:'الشريك المناسب · عملية مضبوطة · مسؤولية واحدة',
scopeEyebrow:'نطاق التوريد',scope1:'نطاق',scope2:'التوريد الصناعي',scopeLead:'حلول توريد منسقة تغطي مجموعة واسعة من الاحتياجات الصناعية',g1:'الصلب والمواد الخام',g2:'الأنابيب والوصلات والصمامات',g3:'المضخات والصمامات ومعدات التدفق',g4:'المحركات وعلب التروس ونقل الحركة',g5:'الكهرباء والأتمتة وأجهزة القياس',g6:'الأنظمة الهيدروليكية والهوائية',g7:'الصوامع ومعدات مناولة المواد السائبة',g8:'الهياكل الفولاذية والتصنيع',g9:'المنشآت الصناعية وحزم الحلول',scopeFoot:'ننظم المصدر المناسب وفق المواصفات الفنية والتطبيق وأهداف التسليم',
sysEyebrow:'الأنظمة المتخصصة',sys1:'الأنظمة',sys2:'المتخصصة',sysLead:'اضغط على أي نظام لعرض النطاق والمحتوى النموذجي وتفاصيل التنسيق',sysA:'محطات الخرسانة',sysB:'مصانع الجلفنة المتكاملة',sysC:'محطات تحويل النفايات إلى طاقة',sysD:'محطات التكسير والغربلة',tap:'عرض التفاصيل',
contactEyebrow:'اتصل بنا',contact1:'تواصل',contact2:'معنا',contactLead:'تواصل مع فريقنا لاحتياجات التوريد الصناعي وتوريد المشاريع والحلول المتخصصة',rfq:'طلب عرض سعر',detailEyebrow:'نظام متخصص',dScope:'النطاق',dTypical:'المحتوى النموذجي',dCoord:'التنسيق'
}};
let currentLang='tr';
function setLang(l){currentLang=l;document.documentElement.lang=l;document.documentElement.dir=l==='ar'?'rtl':'ltr';document.querySelectorAll('.lang').forEach(b=>{b.classList.toggle('active',b.dataset.lang===l);b.setAttribute('aria-pressed',b.dataset.lang===l?'true':'false')});document.querySelectorAll('[data-i]').forEach(el=>{const k=el.dataset.i;el.innerHTML=l==='tr'?(original[k]??el.innerHTML):(strings[l]?.[k]??original[k]??el.innerHTML)})}
document.querySelectorAll('.lang').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));

const detail={
concrete:{img:'/images/beton/prj-1.webp',tr:{title:'Beton Santralleri',scope:'Beton santrali ekipmanlarının tedariki, saha koşullarına uygun sistem çözümü ve teslimat koordinasyonu',list:['Mikser ve karıştırma sistemleri','Agrega bunkerleri ve bantlar','Çimento siloları','Dozaj ve otomasyon ekipmanları'],coord:'Saha yerleşimi, lojistik, montaj desteği ve proje takvimine uyumlu teslimat yönetimi'},en:{title:'Concrete Plants',scope:'Supply of concrete plant equipment, site-adapted system solutions and coordinated delivery',list:['Mixing systems','Aggregate bunkers and conveyors','Cement silos','Dosing and automation'],coord:'Site layout, logistics, installation support and delivery aligned with the project schedule'},ar:{title:'محطات الخرسانة',scope:'توريد معدات محطات الخرسانة وحلول الأنظمة الملائمة للموقع وتنسيق التسليم',list:['أنظمة الخلط','حاويات الركام والسيور','صوامع الأسمنت','أنظمة الجرعات والأتمتة'],coord:'تنسيق تخطيط الموقع والخدمات اللوجستية ودعم التركيب والتسليم وفق برنامج المشروع'}},
galv:{img:'/images/galvaniz/galvaniz1.jpg',tr:{title:'Komple Galvaniz Tesisleri',scope:'Galvaniz hattının ana ekipmanları, proses bölümleri ve yardımcı sistemlerinin entegre tedarik ve koordinasyonu',list:['Yükleme ve taşıma sistemleri','Ön işlem banyoları','Çinko kazanı ve ısıtma sistemleri','Soğutma ve pasivasyon','Kurutma ve son işlem bölümleri'],coord:'Teknik detaylar, üretim takibi, saha koordinasyonu ve devreye alma sürecinin tek noktadan yönetimi'},en:{title:'Complete Galvanizing Plants',scope:'Integrated sourcing and coordination of main line equipment, process sections and auxiliary systems',list:['Loading and handling','Pretreatment baths','Zinc kettle and heating','Cooling and passivation','Drying and finishing'],coord:'Single-point coordination of technical details, production follow-up, site interfaces and commissioning'},ar:{title:'مصانع الجلفنة المتكاملة',scope:'توريد وتنسيق متكامل للمعدات الرئيسية وأقسام العملية والأنظمة المساعدة لخط الجلفنة',list:['أنظمة التحميل والمناولة','أحواض المعالجة المسبقة','حوض الزنك وأنظمة التسخين','التبريد والتخميل','التجفيف والتشطيب'],coord:'إدارة موحدة للتفاصيل الفنية ومتابعة الإنتاج وتنسيق الموقع والتشغيل'}},
waste:{img:'/images/dönüşüm/waste-to-energy.jpg',tr:{title:'Atıktan Enerji Tesisleri',scope:'Atıktan enerji çözüm paketlerinde ekipman, imalat, lojistik ve saha süreçlerinin koordinasyonu',list:['Atık kabul ve besleme','Yakma ünitesi','Kazan ve buhar çevrimi','Türbin-jeneratör','Baca gazı temizleme','Kül yönetimi'],coord:'Ekipman üreticileri, alt yükleniciler ve saha ekipleri arasında teknik ve ticari koordinasyon'},en:{title:'Waste-to-Energy Plants',scope:'Coordination of equipment, fabrication, logistics and site execution for waste-to-energy solution packages',list:['Waste reception and feeding','Combustion unit','Boiler and steam cycle','Turbine-generator','Flue gas treatment','Ash handling'],coord:'Technical and commercial coordination between equipment manufacturers, subcontractors and site teams'},ar:{title:'محطات تحويل النفايات إلى طاقة',scope:'تنسيق المعدات والتصنيع والخدمات اللوجستية والتنفيذ الموقعي لحزم حلول تحويل النفايات إلى طاقة',list:['استقبال وتغذية النفايات','وحدة الاحتراق','الغلاية ودورة البخار','التوربين والمولد','معالجة غازات المداخن','مناولة الرماد'],coord:'التنسيق الفني والتجاري بين مصنعي المعدات والمقاولين وفرق الموقع'}},
crush:{img:'/images/kırma/mobile-crushing-screening-plant-1.jpeg',tr:{title:'Kırma ve Eleme Tesisleri',scope:'Projeye özel kırma ve eleme tesisi için ana ekipman ve yardımcı sistemlerin koordineli tedariki',list:['Besleme sistemleri','Kırıcılar','Titreşimli elekler','Konveyör bant sistemleri','Toz kontrol ekipmanları'],coord:'Uyumlu ekipman seçimi, teknik dokümantasyon, lojistik, gümrük ve saha desteğinin koordinasyonu'},en:{title:'Crushing & Screening Plants',scope:'Coordinated supply of main equipment and auxiliary systems for project-specific crushing and screening plants',list:['Feeding systems','Crushers','Vibrating screens','Conveyors','Dust control equipment'],coord:'Coordination of compatible equipment selection, technical documentation, logistics, customs and site support'},ar:{title:'محطات التكسير والغربلة',scope:'توريد منسق للمعدات الرئيسية والأنظمة المساعدة لمحطات التكسير والغربلة الخاصة بالمشروع',list:['أنظمة التغذية','الكسارات','الشاشات الاهتزازية','السيور الناقلة','معدات التحكم بالغبار'],coord:'تنسيق اختيار المعدات المتوافقة والوثائق الفنية والخدمات اللوجستية والجمارك ودعم الموقع'}}
};
const sheet=document.getElementById('sheet'),sheetImg=document.getElementById('sheetImg'),sheetTitle=document.getElementById('sheetTitle'),sheetScope=document.getElementById('sheetScope'),sheetList=document.getElementById('sheetList'),sheetCoord=document.getElementById('sheetCoord');
document.querySelectorAll('.system-card').forEach(b=>b.onclick=()=>{const d=detail[b.dataset.system],x=d[currentLang]||d.en||d.tr;sheetImg.src=d.img;sheetImg.alt=x.title;sheetTitle.textContent=x.title;sheetScope.textContent=x.scope;sheetList.innerHTML=x.list.map(v=>`<li>${v}</li>`).join('');sheetCoord.textContent=x.coord;sheet.classList.add('open');sheet.scrollTop=0});
document.getElementById('closeSheet').onclick=()=>sheet.classList.remove('open');
document.getElementById('shareBtn').onclick=async()=>{try{if(navigator.share)await navigator.share({title:'VORQA Global Supply',text:'VORQA Interactive Company Profile',url:location.href});else{await navigator.clipboard.writeText(location.href);alert(currentLang==='tr'?'Bağlantı kopyalandı':'Link copied')}}catch(e){}};
