const SITE='https://www.vorqaglobal.com';

const topics={
  'industrial-procurement':{
    slugs:{en:'industrial-procurement-strategic-sourcing',tr:'endustriyel-satinalma-stratejik-tedarik',ar:'industrial-procurement'},
    en:{title:'Industrial Procurement & Strategic Sourcing',keyword:'industrial procurement and strategic sourcing',description:'How to define requirements, qualify suppliers, compare technical-commercial offers and reduce sourcing risk for international industrial projects.'},
    tr:{title:'Endüstriyel Satınalma & Stratejik Tedarik',keyword:'endüstriyel satınalma ve stratejik tedarik',description:'Uluslararası endüstriyel projelerde ihtiyacın tanımlanması, tedarikçi değerlendirme, teknik-ticari karşılaştırma ve tedarik riskinin azaltılması.'},
    ar:{title:'المشتريات الصناعية والتوريد الاستراتيجي',keyword:'المشتريات الصناعية والتوريد الاستراتيجي',description:'منهجيات تحديد المتطلبات وتأهيل الموردين ومقارنة العروض فنياً وتجارياً وتقليل مخاطر التوريد للمشاريع الصناعية الدولية.'},
    articles:[['Supply Chain 2026: Fragilities and Risk','/vorqa-blog/tedarik-zinciri-2026-kirilganliklari-2026-03-05.html']]
  },
  'project-supply':{
    slugs:{en:'project-supply-coordination',tr:'proje-tedariki-koordinasyon',ar:'project-supply'},
    en:{title:'Project Supply & Coordination',keyword:'project supply and coordination',description:'Methods for multi-supplier project purchasing, documentation, quality, schedule, logistics and delivery coordination from requirement to site.'},
    tr:{title:'Proje Tedariği & Koordinasyon',keyword:'proje tedariği ve koordinasyon',description:'Çok tedarikçili projelerde satınalma, dokümantasyon, kalite, termin, lojistik ve sahaya teslim koordinasyonu için uygulama rehberleri.'},
    ar:{title:'توريد المشاريع والتنسيق',keyword:'توريد المشاريع والتنسيق',description:'إرشادات عملية لإدارة الشراء متعدد الموردين والتوثيق والجودة والجدول واللوجستيات والتسليم من المتطلب حتى الموقع.'},
    articles:[['EPC Management: Earned Value & Risk','/vorqa-blog/epc-yonetimi-kazanilmis-deger-risk-2026-01-28.html'],['EPC-F Model and AI','/vorqa-blog/enerji-sektorunde-epc-f-modeli-ve-yapay-zeka-gelecegin-projelerin-2026-05-28.html']]
  },
  'concrete-plants':{
    slugs:{en:'concrete-plants',tr:'beton-santralleri',ar:'concrete-plants'},
    en:{title:'Concrete Plants Knowledge Hub',keyword:'concrete batching plants',description:'Technical decision guides for capacity, mobile vs stationary configuration, component selection, RFQ preparation and supplier comparison for concrete batching plants.'},
    tr:{title:'Beton Santralleri Bilgi Merkezi',keyword:'beton santralleri',description:'Beton santrallerinde kapasite, mobil-sabit seçim, ekipman konfigürasyonu, RFQ hazırlama ve tedarikçi karşılaştırmasına yönelik teknik karar rehberleri.'},
    ar:{title:'مركز معرفة محطات الخرسانة',keyword:'محطات خلط الخرسانة',description:'أدلة قرار فنية للسعة واختيار المحطة المتنقلة أو الثابتة وإعداد طلب العرض ومقارنة الموردين لمحطات خلط الخرسانة.'},
    articles:[['Concrete Plant Capacity Calculation','LOCAL_CONCRETE'],['Mobile vs Stationary Concrete Plant ROI','/vorqa-blog/mobil-sabit-beton-santrali-roi-2026-02-14.html']]
  },
  'galvanizing-plants':{
    slugs:{en:'galvanizing-plants',tr:'galvaniz-tesisleri',ar:'galvanizing-plants'},
    en:{title:'Galvanizing Plants Knowledge Hub',keyword:'hot-dip galvanizing plants',description:'Technical guidance on complete hot-dip galvanizing lines, ISO 1461, coating thickness, process equipment, lifecycle cost and supplier evaluation.'},
    tr:{title:'Galvaniz Tesisleri Bilgi Merkezi',keyword:'sıcak daldırma galvaniz tesisleri',description:'Komple sıcak daldırma galvaniz hatları, ISO 1461, kaplama kalınlığı, proses ekipmanları, yaşam döngüsü maliyeti ve tedarikçi değerlendirme rehberleri.'},
    ar:{title:'مركز معرفة مصانع الجلفنة',keyword:'مصانع الجلفنة بالغمس الساخن',description:'إرشادات فنية لخطوط الجلفنة الكاملة ومعيار ISO 1461 وسماكة الطلاء ومعدات العملية وتكلفة دورة الحياة وتقييم الموردين.'},
    articles:[['ISO 1461: Coating Thickness & Service Life','/vorqa-blog/iso-1461-galvaniz-kaplama-kalinligi-2026-04-22.html'],['Galvanizing vs Paint: Lifecycle Cost','/vorqa-blog/galvaniz-boya-kaplama-yasam-dongusu-maliyeti-2026-06-25.html']]
  },
  'waste-to-energy':{
    slugs:{en:'waste-to-energy',tr:'atiktan-enerji',ar:'waste-to-energy'},
    en:{title:'Waste-to-Energy Knowledge Hub',keyword:'waste-to-energy projects',description:'Decision support for waste characterization, technology selection, project interfaces, RFQ scope and supplier evaluation in waste-to-energy projects.'},
    tr:{title:'Atıktan Enerjiye Bilgi Merkezi',keyword:'atıktan enerji projeleri',description:'Atık karakterizasyonu, teknoloji seçimi, proje arayüzleri, RFQ kapsamı ve tedarikçi değerlendirmesi için karar destek içerikleri.'},
    ar:{title:'مركز معرفة تحويل النفايات إلى طاقة',keyword:'مشاريع تحويل النفايات إلى طاقة',description:'محتوى دعم القرار لتوصيف النفايات واختيار التقنية وتحديد نطاق طلب العرض وتقييم الموردين في مشاريع تحويل النفايات إلى طاقة.'},
    articles:[['Waste-to-Energy Technologies','/vorqa-blog/wte-atiktan-enerjiye-teknolojiler-2026-04-08.html'],['EPC-F Model and AI','/vorqa-blog/enerji-sektorunde-epc-f-modeli-ve-yapay-zeka-gelecegin-projelerin-2026-05-28.html']]
  },
  'crushing-screening':{
    slugs:{en:'crushing-screening',tr:'kirma-eleme',ar:'crushing-screening'},
    en:{title:'Crushing & Screening Knowledge Hub',keyword:'crushing and screening plants',description:'Technical guides for feed material, capacity, crusher and screen selection, mobile vs stationary configuration, RFQ scope and supplier comparison.'},
    tr:{title:'Kırma & Eleme Bilgi Merkezi',keyword:'kırma ve eleme tesisleri',description:'Besleme malzemesi, kapasite, kırıcı-elek seçimi, mobil-sabit konfigürasyon, RFQ kapsamı ve tedarikçi karşılaştırması için teknik rehberler.'},
    ar:{title:'مركز معرفة التكسير والغربلة',keyword:'محطات التكسير والغربلة',description:'أدلة فنية لمادة التغذية والسعة واختيار الكسارات والغرابيل والتكوين المتنقل أو الثابت ونطاق طلب العرض ومقارنة الموردين.'},
    articles:[['Mechanical Installation: Vibration & Alignment','/vorqa-blog/mekanik-montaj-titresim-analizi-hizalama-2026-06-11.html']]
  }
};

const ui={
 en:{academy:'Academy',home:'Home',contact:'Contact / RFQ',eyebrow:'VORQA ACADEMY · KNOWLEDGE HUB',intro:'This is a technical knowledge hub, not a product catalogue. It organizes decision criteria, procurement questions and field-oriented guidance so buyers can define requirements and compare suppliers more effectively.',questions:'Questions this hub helps answer',read:'Related Academy research',related:'Related knowledge hubs',how:'How VORQA uses this knowledge',howtext:'VORQA works on the customer side: requirement clarification, supplier route development, technical-commercial comparison, documentation, quality and delivery coordination. Knowledge pages support the decision process; commercial scope is confirmed through an RFQ.',cta:'Have a live requirement?',ctabody:'Send the available specification, drawing, datasheet, target capacity or application. We will structure the requirement before approaching suitable suppliers.',button:'Send an RFQ',sources:'Source discipline',sourcetext:'Technical claims should be traceable to standards, manufacturer documentation, project data or clearly identified engineering assumptions. AI-assisted content is reviewed against VORQA truth rules before publication.',q:['What information must be fixed before an RFQ is issued?','Which technical parameters actually change supplier selection and price?','How should offers be normalized before commercial comparison?','Which quality, documentation, logistics and schedule risks should be checked?']},
 tr:{academy:'Akademi',home:'Ana Sayfa',contact:'İletişim / RFQ',eyebrow:'VORQA AKADEMİ · BİLGİ MERKEZİ',intro:'Bu sayfa bir ürün kataloğu değildir. Satınalma kararlarını güçlendirmek için teknik karar kriterlerini, RFQ sorularını ve saha odaklı rehberleri aynı konu altında toplar.',questions:'Bu merkez hangi sorulara cevap verir?',read:'İlgili Akademi araştırmaları',related:'İlgili bilgi merkezleri',how:'VORQA bu bilgiyi nasıl kullanır?',howtext:'VORQA müşteri tarafında çalışır: ihtiyacın netleştirilmesi, uygun tedarikçi rotalarının kurulması, teknik-ticari karşılaştırma, dokümantasyon, kalite ve teslimat koordinasyonu. Bilgi sayfaları karar sürecini destekler; ticari kapsam RFQ üzerinden netleşir.',cta:'Aktif bir ihtiyacınız mı var?',ctabody:'Mevcut şartnameyi, çizimi, datasheet’i, hedef kapasiteyi veya uygulamayı gönderin. Uygun tedarikçilere çıkmadan önce ihtiyacı yapılandırırız.',button:'RFQ Gönder',sources:'Kaynak disiplini',sourcetext:'Teknik iddialar standartlara, üretici dokümanlarına, proje verisine veya açıkça belirtilmiş mühendislik varsayımlarına izlenebilir olmalıdır. AI destekli içerik yayınlanmadan önce VORQA truth kurallarıyla kontrol edilir.',q:['RFQ yayınlanmadan önce hangi bilgiler kesinleşmeli?','Hangi teknik parametreler tedarikçi seçimini ve fiyatı gerçekten değiştirir?','Teklifler ticari karşılaştırmadan önce nasıl normalize edilmeli?','Kalite, dokümantasyon, lojistik ve termin açısından hangi riskler kontrol edilmeli?']},
 ar:{academy:'الأكاديمية',home:'الرئيسية',contact:'اتصال / طلب عرض',eyebrow:'أكاديمية VORQA · مركز معرفة',intro:'هذه الصفحة ليست كتالوج منتجات. إنها تجمع معايير القرار الفني وأسئلة طلب العرض والإرشادات العملية تحت موضوع واحد لمساعدة المشترين على تعريف الاحتياج ومقارنة الموردين بوضوح.',questions:'ما الأسئلة التي يساعد هذا المركز على الإجابة عنها؟',read:'أبحاث أكاديمية مرتبطة',related:'مراكز معرفة مرتبطة',how:'كيف تستخدم VORQA هذه المعرفة؟',howtext:'تعمل VORQA من جهة العميل: توضيح المتطلبات، بناء مسارات الموردين، المقارنة الفنية والتجارية، التوثيق، الجودة وتنسيق التسليم. صفحات المعرفة تدعم القرار، أما النطاق التجاري فيتأكد من خلال طلب عرض.',cta:'لديك احتياج فعلي؟',ctabody:'أرسل المواصفة أو الرسم أو ورقة البيانات أو السعة المستهدفة أو التطبيق المتاح. نقوم أولاً بتنظيم المتطلب قبل التواصل مع الموردين المناسبين.',button:'إرسال طلب عرض',sources:'انضباط المصادر',sourcetext:'يجب أن تكون الادعاءات الفنية قابلة للتتبع إلى معايير أو وثائق مصنع أو بيانات مشروع أو افتراضات هندسية موضحة. تتم مراجعة المحتوى المدعوم بالذكاء الاصطناعي وفق قواعد VORQA قبل النشر.',q:['ما المعلومات التي يجب تثبيتها قبل إصدار طلب العرض؟','ما المعايير الفنية التي تؤثر فعلاً في اختيار المورد والسعر؟','كيف يجب توحيد العروض قبل المقارنة التجارية؟','ما مخاطر الجودة والتوثيق واللوجستيات والجدول التي يجب فحصها؟']}
};

const paths={en:{base:'/en/academy/',home:'/en/',contact:'/en/contact/'},tr:{base:'/tr/akademi/',home:'/tr/',contact:'/tr/iletisim/'},ar:{base:'/ar/academy/',home:'/ar/',contact:'/ar/contact/'}};
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const hubUrl=(key,lang)=>`${SITE}${paths[lang].base}${topics[key].slugs[lang]}/`;

function page(topicKey,lang){
 const topic=topics[topicKey]; const t=topic[lang]; const u=ui[lang]; const p=paths[lang]; const canonical=hubUrl(topicKey,lang); const dir=lang==='ar'?'rtl':'ltr';
 const alternates=['tr','en','ar'].map(l=>`<link rel="alternate" hreflang="${l}" href="${hubUrl(topicKey,l)}">`).join('')+`<link rel="alternate" hreflang="x-default" href="${hubUrl(topicKey,'en')}">`;
 const articleLinks=topic.articles.map(([label,href])=>{const url=href==='LOCAL_CONCRETE'?`${p.base}beton-santrali-kapasite-hesaplama-2026-05-10/`:href;return `<a href="${url}">${esc(label)}</a>`}).join('');
 const related=Object.keys(topics).filter(k=>k!==topicKey).map(k=>`<a href="${paths[lang].base}${topics[k].slugs[lang]}/">${esc(topics[k][lang].title)}</a>`).join('');
 const schema={"@context":"https://schema.org","@type":"WebPage",name:t.title,url:canonical,description:t.description,inLanguage:lang,isPartOf:{"@type":"WebSite",name:'VORQA Global',url:SITE+'/'},about:{"@type":"Thing",name:t.keyword},publisher:{"@type":"Organization",name:'VORQA Global',url:SITE+'/'}};
 const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:u.home,item:SITE+p.home},{"@type":"ListItem",position:2,name:u.academy,item:SITE+p.base},{"@type":"ListItem",position:3,name:t.title,item:canonical}]};
 const css=':root{--i:#0A2540;--b:#2874B2;--m:#5d6b79;--l:#dbe6ef;--g:#f5f9fc;--o:#E87722}*{box-sizing:border-box}body{margin:0;background:var(--g);color:var(--i);font:16px/1.65 Arial,"Noto Sans Arabic",sans-serif}a{color:inherit}.w{max-width:1080px;margin:auto;padding:0 24px}.n{background:#071a2b;color:#fff}.n .w{min-height:72px;display:flex;align-items:center;justify-content:space-between;gap:20px}.logo{height:42px;background:#fff;border-radius:4px;padding:5px 8px}.links{display:flex;gap:18px}.links a{text-decoration:none;font-size:14px}.hero{padding:82px 0 58px;background:linear-gradient(145deg,#071a2b,#0A2540);color:#fff}.eye{font-size:12px;letter-spacing:.14em;color:#9dc7ea}h1{font-size:clamp(2.2rem,5vw,4.2rem);line-height:1.05;margin:.35em 0}.lead{max-width:850px;font-size:1.12rem;color:#d7e6f3}.cr{font-size:13px;color:#687989;padding:20px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.card{background:#fff;border:1px solid var(--l);border-radius:14px;padding:26px}section{padding:28px 0}h2{margin:0 0 15px;font-size:1.55rem}li{margin:.55em 0}.alist{display:grid;gap:10px}.alist a{display:block;text-decoration:none;background:#fff;border:1px solid var(--l);padding:15px 17px;border-radius:9px}.cta{background:var(--i);color:#fff;border-radius:15px;padding:32px}.cta p{color:#d6e5f2}.btn{display:inline-block;text-decoration:none;background:var(--o);padding:11px 17px;border-radius:8px;font-weight:700}footer{margin-top:42px;background:#071a2b;color:#c7d8e8;padding:28px 0;font-size:13px}@media(max-width:760px){.grid{grid-template-columns:1fr}.n .w{padding-top:12px;padding-bottom:12px}.hero{padding-top:58px}}';
 return `<!doctype html><html lang="${lang}" dir="${dir}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(t.title)} | VORQA Academy</title><meta name="description" content="${esc(t.description)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"><link rel="canonical" href="${canonical}">${alternates}<meta property="og:type" content="website"><meta property="og:site_name" content="VORQA Global"><meta property="og:title" content="${esc(t.title)} | VORQA Academy"><meta property="og:description" content="${esc(t.description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${SITE}/og-default.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/favicon.svg"><script type="application/ld+json">${JSON.stringify(schema)}</script><script type="application/ld+json">${JSON.stringify(breadcrumb)}</script><style>${css}</style></head><body><nav class="n"><div class="w"><a href="${p.home}"><img class="logo" src="/brand_assets/vorqa_logo_main_cropped.png" alt="VORQA Global"></a><div class="links"><a href="${p.base}">${u.academy}</a><a href="${p.contact}">${u.contact}</a></div></div></nav><header class="hero"><div class="w"><div class="eye">${u.eyebrow}</div><h1>${esc(t.title)}</h1><p class="lead">${esc(t.description)}</p></div></header><main class="w"><div class="cr"><a href="${p.home}">${u.home}</a> · <a href="${p.base}">${u.academy}</a> · ${esc(t.title)}</div><section><div class="grid"><article class="card"><h2>${u.questions}</h2><ul>${u.q.map(x=>`<li>${x}</li>`).join('')}</ul></article><article class="card"><h2>${u.how}</h2><p>${u.howtext}</p></article></div></section><section><h2>${u.read}</h2><div class="alist">${articleLinks}</div></section><section><h2>${u.related}</h2><div class="alist">${related}</div></section><section><div class="card"><h2>${u.sources}</h2><p>${u.sourcetext}</p><p>${u.intro}</p></div></section><section><div class="cta"><h2>${u.cta}</h2><p>${u.ctabody}</p><a class="btn" href="${p.contact}">${u.button}</a></div></section></main><footer><div class="w">VORQA Global · From requirement to delivery · Ankara, Türkiye</div></footer></body></html>`;
}

export default function handler(req,res){
 const lang=String(req.query.lang||'en'); const topicKey=String(req.query.topic||'');
 if(!['en','tr','ar'].includes(lang)||!topics[topicKey]) return res.status(404).send('Not found');
 res.setHeader('Content-Type','text/html; charset=utf-8');
 res.setHeader('Cache-Control','public, max-age=0, s-maxage=86400, stale-while-revalidate=604800');
 return res.status(200).send(page(topicKey,lang));
}
