import fs from 'node:fs';
const SITE='https://www.vorqaglobal.com';
const files={en:new URL('../en/academy/index.html',import.meta.url),tr:new URL('../tr/akademi/index.html',import.meta.url),ar:new URL('../ar/academy/index.html',import.meta.url)};
const maps={en:'/en/academy/knowledge-map/',tr:'/tr/akademi/bilgi-haritasi/',ar:'/ar/academy/knowledge-map/'};
const copy={en:{ey:'ACADEMY KNOWLEDGE MAP',title:'Explore by decision, not by product',body:'Start from industrial procurement, project supply or a technical plant decision. Six knowledge hubs connect practical questions, Academy research and the RFQ path.',button:'Open Knowledge Map'},tr:{ey:'AKADEMİ BİLGİ HARİTASI',title:'Üründen değil, vermeniz gereken karardan başlayın',body:'Endüstriyel satınalma, proje tedariği veya teknik tesis kararından başlayın. Altı bilgi merkezi; pratik soruları, Academy araştırmalarını ve RFQ yolunu birbirine bağlar.',button:'Bilgi Haritasını Aç'},ar:{ey:'خريطة معرفة الأكاديمية',title:'ابدأ بالقرار وليس بقائمة المنتجات',body:'ابدأ بالمشتريات الصناعية أو توريد المشاريع أو القرار الفني للمصنع. ستة مراكز معرفة تربط الأسئلة العملية بأبحاث الأكاديمية ومسار طلب العرض.',button:'فتح خريطة المعرفة'}};
function injectHead(html){const tags=`<link rel="alternate" hreflang="tr" href="${SITE}/tr/akademi/"><link rel="alternate" hreflang="en" href="${SITE}/en/academy/"><link rel="alternate" hreflang="ar" href="${SITE}/ar/academy/"><link rel="alternate" hreflang="x-default" href="${SITE}/en/academy/">`;return /hreflang=/i.test(html)?html:html.replace(/<\/head>/i,`${tags}</head>`)}
function band(lang){const t=copy[lang];return `<section id="knowledge-map-entry" aria-labelledby="knowledge-map-title" style="background:#071a2b;color:#fff;padding:54px 24px;border-top:1px solid rgba(40,116,178,.35);border-bottom:1px solid rgba(40,116,178,.25)"><div style="max-width:1080px;margin:0 auto;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:28px;align-items:center"><div><div style="font:600 11px/1.3 monospace;letter-spacing:.16em;color:#8fc0e7;margin-bottom:12px">${t.ey}</div><h2 id="knowledge-map-title" style="font:400 clamp(1.7rem,4vw,2.7rem)/1.12 Arial,sans-serif;margin:0 0 12px">${t.title}</h2><p style="max-width:760px;margin:0;color:#d3e2ef;line-height:1.7">${t.body}</p></div><a href="${maps[lang]}" style="display:inline-block;background:#E87722;color:#fff;text-decoration:none;font-weight:700;padding:12px 18px;border-radius:8px;white-space:nowrap">${t.button} →</a></div></section><style>@media(max-width:760px){#knowledge-map-entry>div{grid-template-columns:1fr!important}#knowledge-map-entry a{justify-self:start}}</style>`}
function injectBody(html,lang){const b=band(lang);if(html.includes('id="knowledge-map-entry"'))return html;if(/<footer\b/i.test(html))return html.replace(/<footer\b/i,`${b}<footer`);return html.replace(/<\/body>/i,`${b}</body>`)}
export default function handler(req,res){const lang=['tr','ar'].includes(req.query.lang)?req.query.lang:'en';try{let html=fs.readFileSync(files[lang],'utf8');html=injectBody(injectHead(html),lang);res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','public, s-maxage=3600, stale-while-revalidate=86400');res.status(200).send(html)}catch(err){console.error('ACADEMY_INDEX_INJECT_FAILED',lang,err);res.status(500).send('Academy temporarily unavailable')}}
